config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount HealthMonitor::Engine, at: "/"
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => "/"
  mount Arclight::Engine => "/"
  mount BlacklightDynamicSitemap::Engine => "/"

  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: "catalog", path: "/catalog", controller: "catalog" do
    concerns :searchable
    concerns :range_searchable
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:passwords, :registration]
  devise_scope :user do
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    get "users/auth/cas", to: "users/omniauth_authorize#passthru", defaults: { provider: :cas }, as: "new_user_session"
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  require "sidekiq/web"
  authenticate :user,  ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end

  # Redirect requests in the form of legacy URL syntax to their new location.
  # Keep the entire eadid as passed, even if it contains dots. Replace the dots
  # with dashes in the redirect.
  get "/collections/:eadid/:componentid", constraints: { eadid: /([^\/])+?/ }, to: redirect { |params, _request|
    "/catalog/#{params[:eadid].tr('.', '-')}_#{params[:componentid]}"
  }

  get "/collections/:eadid", constraints: { eadid: /([^\/])+?/ }, format: /json|xml|html/, to: redirect { |params, _request|
    "/catalog/#{params[:eadid].tr('.', '-')}"
  }

  get "/toc", to: "toc#toc", as: "toc"
  get "/toc/:node/child_table", to: "toc#child_table", as: "toc_child_table"
  get "/hours", to: "hours#hours"
  get "/research_help", to: "about#research_help"
  get "/search_tips", to: "about#search_tips"
  get "/faq", to: "about#faq"
  get "/av_materials", to: "about#av_materials"
  get "/requesting_materials", to: "about#requesting_materials"
  get "/research_account", to: "about#research_account"
  get "/archival_language", to: "about#archival_language"
  get "/ask_a_question", to: "feedback#ask_a_question"
  get "/suggest", to: "feedback#suggest"
  get "/report", to: "feedback#report"
  post "/contact/suggest", to: "contact#suggest"
  post "/contact/question", to: "contact#question"
  post "/contact/report", to: "contact#report"

  get "/pacscl/production", to: "partner_exports#pacscl"
  get "/pacscl/production/:id", to: "partner_exports#pacscl_xml", as: :pacscl_xml

  match "*unmatched", to: "application#route_not_found", via: :all
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

class CatalogController < ApplicationController
  include Blacklight::Catalog
  include Arclight::Catalog
  include Arclight::FieldConfigHelpers
  include BlacklightRangeLimit::ControllerOverride
  include MultipleAlgorithms

  # This should be unnecessary with an update ArcLight or Blacklight upstream
  def raw
    raise(ActionController::RoutingError, "Not Found") unless blacklight_config.raw_endpoint.enabled

    _, @document = search_service.fetch(params[:id])
    render json: @document.as_json
  end

  def index
    query_param = params[:q]
    match = /^(aspace_)?(?<identifier>[A-z]{1,2}\d{3,4})([.-].*)?(_[0-9]?c.*)?$/.match(query_param)
    return super unless match

    # Try and take the user directly to the show page
    id = query_param.tr(".", "-").gsub(match[:identifier], match[:identifier].upcase)
    _response, doc = search_service.fetch(id)
    @document = doc
    redirect_to solr_document_path(id: @document)
  rescue Blacklight::Exceptions::RecordNotFound
    super
  end

  # @see Blacklight::Catalog#show
  def show
    deprecated_response, @document = search_service.fetch(params[:id])
    @response = ActiveSupport::Deprecation::DeprecatedObjectProxy.new(
      deprecated_response,
      "The @response instance variable is deprecated; use @document.response instead.",
      ActiveSupport::Deprecation.new
    )

    respond_to do |format|
      format.html do
        @search_context = setup_next_and_previous_documents
        if document_expanded?
          show_view_config = blacklight_config.view_config(:show)
          updated_partials = show_view_config.partials.reject { |p| p == :show }
          updated_partials << :show_collection_expanded
          blacklight_config.view_config(:show).partials = updated_partials

          @document_tree = build_document_tree
        end
      end
      @document.suppress_xml_containers! if params[:containers].to_s == "false"
      format.json do
        render json: @document.to_json
      end
      additional_export_formats(@document, format)
    end
  rescue Blacklight::Exceptions::RecordNotFound => e
    raise e unless display_unpublished_aspace_record
  end

  # Check aspace for an unpublished record that wasn't found in the index
  def display_unpublished_aspace_record
    return unless request.format == :json && params[:auth_token].to_s == Pulfalight.config["unpublished_auth_token"]
    client = Aspace::Client.new
    record = client.get_basic_info(id: params[:id])
    return unless record
    record["id"] = record["ref_id"] || record["identifier"]
    render json: record.to_json
  rescue StandardError => e
    # errors pass through as 404s, but let's at least log them.
    Rails.logger.error e.message
    raise e
  end

  # Set allowed search alorithm parameter values
  # See: multiple_algorithms.rb
  MultipleAlgorithms.allowed_search_algorithms = ["default", "online_content"]

  configure_blacklight do |config|
    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response

    config.raw_endpoint.enabled = true

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      rows: 10
    }

    # solr path which will be added to solr base url before the other solr params.
    # config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    # config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blacklight defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    # config.default_document_solr_params = {
    #  qt: 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # fl: '*',
    #  # rows: 1,
    #  # q: '{!term f=id v=$id}'
    # }

    config.default_document_solr_params = {
      fl: "*"
    }

    # solr field configuration for search results/index views
    config.index.title_field = "normalized_title_ssm"
    config.index.display_type_field = "level_ssm"
    # config.index.thumbnail_field = 'thumbnail_path_ss'

    # solr field configuration for document/show views
    # config.show.title_field = 'title_display'
    config.show.display_type_field = "level_ssm"
    # config.show.thumbnail_field = 'thumbnail_path_ss'

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:algorithm_select)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    config.add_show_tools_partial(:citation)

    config.add_nav_action(:search_history, partial: "blacklight/nav/search_history")

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    config.add_facet_field "has_direct_online_content_ssim", label: "Access", collapse: false, query: {
      online: { label: "Online", fq: "has_direct_online_content_ssim:true" }
    }
    config.add_facet_field "collection_sim", label: "Collection", limit: 10
    config.add_facet_field "creator_ssim", label: "Creator", limit: 10
    config.add_facet_field "creators_ssim", label: "Creator", show: false
    config.add_facet_field "collectors_ssim", label: "Collector", show: false
    config.add_facet_field "date_range_sim", label: "Date range", range: true
    config.add_facet_field "names_ssim", label: "Names", limit: 10
    config.add_facet_field "repository_sim", label: "Repository", limit: 10
    config.add_facet_field "geogname_sim", label: "Place", limit: 10
    config.add_facet_field "places_ssim", label: "Places", show: false
    config.add_facet_field "access_subjects_ssim", label: "Subject", limit: 10
    config.add_facet_field "parent_unittitles_ssim", label: "Series", show: false

    # Facet label configuration for links in component show page.
    config.add_facet_field "topics_ssim", label: "Topics", show: false
    config.add_facet_field "subject_terms_ssim", label: "Subject Terms", show: false
    config.add_facet_field "genreform_ssim", label: "Genre Terms", show: false

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field "unitid_ssm", label: "Unit ID"
    config.add_index_field "repository_ssm", label: "Repository"
    config.add_index_field "normalized_date_ssm", label: "Date"
    config.add_index_field "creator_ssm", label: "Creator"
    config.add_index_field "language_ssm", label: "Language"
    config.add_index_field "scopecontent_ssm", label: "Description", helper_method: :paragraph_separator
    config.add_index_field "extent_ssm", label: "Physical Description"
    config.add_index_field "accessrestrict_ssm", label: "Conditions Governing Access", accessor: :fetch_html_safe
    config.add_index_field "collection_ssm", label: "Collection Title"
    config.add_index_field "geogname_ssm", label: "Place"
    config.add_index_field "access_ssi", label: "Access"

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject

app/views/catalog/_arclight_index_compact_default.html.erb
<div class="documentHeader row">
  <div class="col-auto">
    <%= blacklight_icon document_or_parent_icon(document) %>
  </div>
  <div class="col col-no-left-padding col-no-right-padding">
    <div class="d-flex justify-content-between">
      <h3 class="col col-no-left-padding">
        <%= link_to_document document, document_show_link_field(document), counter: document_counter %>
      </h3>
      <%= render_index_doc_actions document %>
    </div>
    <div class="row">
      <%= content_tag('div', class: 'al-document-highlight col') do %>
        <%= document.highlights.join('<br/>').html_safe %>
        <% end if document.highlights %>
    </div>
    <div class='breadcrumb-links media'>
      <span class="media-body" aria-hidden="true"><%= blacklight_icon :repository, classes: 'al-repository-content-icon' %></span>
      <span class="col ml-2 pl-0" ><%= regular_compact_breadcrumbs(document) %></span>
    </div>
  </div>
</div>

app/views/catalog/_ask_a_question_form.html.erb
<% if form.submitted? %>
  <div class="alert alert-success" role="alert">
    Thank you for submitting your question to Special Collections.
    Someone will reply to you via email soon.
    We appreciate your patience and look forward to addressing your inquiry.
  </div>
<% end %>
<%= simple_form_for form, url: contact_question_path, remote: true do |f| %>
  <%= f.input :name %>
  <%= f.input :email, as: :email %>
  <%= f.input :subject, as: :select, collection: form.subject_options, include_blank: false %>
  <%= f.input :message, as: :text %>
  <%= f.input :location_code, as: :hidden %>
  <%= f.input :context, as: :hidden %>
  <%= f.input :title, as: :hidden %>
  <%= f.submit "Send", class: "btn btn-primary" %>
<% end %>

app/views/catalog/_collection_history.html.erb
<div class="overview document-info">
  <% metadata = :collection_history_field %>
  <% doc_presenter = document_presenter(document).with_field_group(metadata) %>
  <dl>
    <% generic_document_fields(metadata).each do |field_name, field| %>
      <% if generic_should_render_field?(metadata, document, field) %>
        <%= render partial: "catalog/field", locals: { document: document, field: field, field_name: field_name, metadata: metadata, doc_presenter: doc_presenter } %>
      <% end %>
    <% end %>
  </dl>
</div>

app/views/catalog/_collection_summary_abstract.html.erb
<dl>
  <dt><h4>Abstract</h4></dt>
  <% metadata = :abstract_field %>
  <% doc_presenter = document_presenter(document).with_field_group(metadata) %>
  <% generic_document_fields(metadata).each do |field_name, field| %>
    <% if generic_should_render_field?(metadata, document, field) %>
      <dd class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field %></dd>
    <% end %>
  <% end %>
</dl>

app/views/catalog/_component_collection_history.html.erb
<div class="overview">
  <div class="document-title">
    <h3>Collection History</h3>
  </div>
  <% metadata = :collection_history_field %>
  <% doc_presenter = show_presenter(document).with_field_group(metadata) %>
  <dl>
    <% generic_document_fields(metadata).each do |field_name, field| %>
      <% if generic_should_render_field?(metadata, document, field) %>
        <dt class="blacklight-<%= field_name.parameterize %>"><%= generic_render_document_field_label(metadata, document, field: field_name) %></dt>
        <dd class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field %></dd>
      <% end %>
    <% end %>
  </dl>
</div>

app/views/catalog/_correction_modal.html.erb
<% content_for :correction_modal do %>
  <div class="modal fade" id="correctionModal" tabindex="-1" role="dialog" aria-label="Suggest a Correction" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="correctionModalTitle">Suggest a Correction</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body form-wrapper">
          <div class="suggest_a_correction_instructions">
            Please use this area to report errors, omissions, or <a href="https://library.princeton.edu/about/responsible-collection-description" target="_blank">problematic language </a>
            that appear in the description of this collection. Corrections may include
            misspellings, incorrect or missing dates, misidentified individuals, places,
            or events, mislabeled folders, misfiled papers, etc.
          </div>
          <%= render partial: "correction_form", locals: { form: SuggestACorrectionForm.new(location_code: @document.fetch("repository_code_ssm", []).first, context: request.original_url) } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/catalog/_home.html.erb
<div class="container-fluid home">
  <section class="home-text padding">
    <div class="row">
      <div id="hours">
        <%= render "hours" %>
      </div>
      <div id="requests">
        <%= render "requests" %>
      </div>
      <div id="responsible-collection-description">
        <%= render "responsible_collection_description" %>
      </div>
    </div>
  </section>

  <div class="container-fluid spacer"></div>
</div>

app/views/catalog/_index_default.html.erb
<%= content_tag('div', class: 'al-document-creator') do %>
  <%= document.creator %>
<% end if document.creator %>

<%= content_tag('div', class: 'al-document-call-number') do %>
  <%= document.eadid %>
<% end if document.collection? %>

<%= content_tag('div', class: 'al-document-extent') do %>
  <%= document.extent %>
<% end if document.extent %>

<%= content_tag('div', class: 'al-document-abstract-or-scope') do %>
  <%= content_tag('div', 'data-arclight-truncate' => true) do %>
    <%= document.abstract_or_scope %>
  <% end %>
<% end if document.abstract_or_scope %>

<%= content_tag('div', class: 'al-document-highlight') do %>
  <%= document.highlights.join('<br/>').html_safe %>
<% end if document.highlights %>

app/views/catalog/_index_header_hierarchy_default.html.erb
<div class="documentHeader row" data-document-id="<%= document.id %>">
  <% requestable = item_requestable?('', { document: document }) %>
  <h3 class="index_title document-title-heading col-md-8">
    <% if document.containers.present? %>
      <span class="document-title-containers">
        <%= document.container_titles.join(', ') %>:
      </span>
    <% end %>
    <% if document.children? %>
      <% unless hierarchy_component_context? %>
        <%= link_to(
          blacklight_icon(:plus),
          "##{document.reference}-collapsible-hierarchy",
          class: 'al-toggle-view-all',
          'aria-label': t('arclight.hierarchy.view_all'),
            data: {
              toggle: 'collapse'
            }
          )
        %>
      <% end %>
    <% end %>
    <% counter = document_counter_with_offset(document_counter) %>
    <%= link_to_document document, document_show_link_field(document), counter: counter %>
    <% if document.children? %>
      <span class="badge badge-pill badge-secondary al-number-of-children-badge"><%= document.number_of_children %><span class="sr-only"><%= t(:'arclight.views.index.number_of_components', count: document.number_of_children) %></span></span>
    <% end %>
    <%= render_document_partial(document, 'arclight_online_content_indicator') %>
  </h3>

  <div class="al-hierarchy-side-content float-right col">

    <% if requestable %>
      <div class="lux">
        <add-to-cart-button
          callnumber="<%= document.callnumber %>"
          title="<%= document.title %>"
          :unitid=<%= document.unitid_attributes.to_json %>
          :physloc=<%= document.physloc_attributes.to_json %>
          :containers=<%= document.container_attributes.to_json %>>
          <%= t('request.cart', type: document.level.downcase) %>
        </add-to-cart-button>
      </div>
    <% end %>
  </div>
</div>

app/views/catalog/_show_actions_box_default.html.erb
<div class='al-show-actions-box'>
  <div class="al-actions-box-container">
    <% if document.unitid || document.containers.present? %>
      <div class='al-collection-id'>
        <% if document.unitid %>
          <%= document.unitid %>
        <% end %>
      </div>
    <% elsif document.collection_unitid %>
      <div class='al-collection-id'>
        <%= document.collection_unitid %>
      </div>
    <% end %>
  </div>
  <%= render document.downloads %>
</div>

app/views/catalog/_show_collection.html.erb
<% parents = Arclight::Parents.from_solr_document(document).as_parents %>

<div class='row'>
  <div class='col-md-12'>

    <!-- The content tab navigation -->
    <!-- Tabs -->
    <!-- Tabs -->
    <%= render(partial: 'show_tabs') %>

    <div id="toc-container" class="row content-container">
      <div class="col-md-4">
        <div class="toc-header">
          <div class="toc-header-text">
            <span class="text-uppercase">Contents and Arrangement</span>
            <a class="toc-header__expand-button" href="?expanded=true" >
              <%= image_tag(asset_path('icon-expand-alt-solid.svg'), class: 'expand-collection-icon', "aria-label": "expand the collection view") %>
              <span>Expanded View</span>
            </a>
          </div>
          <div class="toc-toggle">
            <a data-bs-toggle="collapse" href="#toc" role="button">
              <span class="visually-hidden">Toggle</span>
              <span class="toggle-icon"></span>
            </a>
          </div>
        </div>
        <div class="toc-online-toggle al-online-material-icon">
          <%= blacklight_icon(:online) %>
          <label for="tocOnlineToggle" class="online-toggle-label">
            <span> Only show material containing online material </span>
           <div class="toggle">
              <input type="checkbox" id="tocOnlineToggle">
              <span class="toc-slider"></span>
          </div>
          </label>
        </div>
        <div id="toc" data-turbolinks-permanent class="collapse show"></div>
        <div id="toc-data" data-selected="<%= document.id %>"></div>
      </div>

      <div class="col-md-8">
        <%= render(partial: 'show_tab_panes') %>
      </div><!-- .col-md-8 -->
    </div><!-- .row.content-container -->
  </div>
</div>

app/views/catalog/_show_collection_expanded.html.erb
<% parents = Arclight::Parents.from_solr_document(document).as_parents %>

<div class='row'>
  <div class='col-md-12'>

    <!-- The content tab navigation -->
    <div class='row content-navigation'>
      <div class='col-md-12'>
        <ul class='nav nav-tabs nav-fill' role='tablist' aria-label='<%= t('arclight.views.show.tablist_nav') %>'>

          <li class='nav-item flex-fill' role='tab'>
            <a class='nav-link active' data-bs-toggle='tab' href='#summary' role='tab' aria-selected="true">
              Overview
            </a>
          </li>
          <li class='nav-item flex-fill' role='tab'>
            <a class='nav-link ' data-bs-toggle='tab' href='#description' role='tab'>
              Collection Description & Creator Information
            </a>
          </li>
          <li class='nav-item flex-fill' role='tab'>
            <a class='nav-link ' data-bs-toggle='tab' href='#access' role='tab'>
              <%= t 'arclight.views.show.access' %>
            </a>
          </li>
          <li class='nav-item flex-fill' role='tab'>
            <a class='nav-link ' data-bs-toggle='tab' href='#collection-history' role='tab'>
              Collection History
            </a>
          </li>
          <li class='nav-item flex-fill' role='tab'>
            <a class='nav-link ' data-bs-toggle='tab' href='#find-more' role='tab'>
              Find Related Materials
            </a>
          </li>
        </ul>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row.content-navigation -->

    <div class="row content-container">
      <div class="col-md-4">
        <div class="toc-header">
          <div class="toc-header-text">
            <span class="text-uppercase">Contents and Arrangement</span>
            <a class="toc-header__expand-button" href="<%= solr_document_url(document) %>">
              <%= image_tag(asset_path('icon-compress-alt-solid.svg'), class: 'compress-collection-icon', "aria-label": "view the collection in the default mode") %>
              <span>Collection View</span>
            </a>
          </div>
          <div class="toc-toggle">
            <a data-bs-toggle="collapse" href="#toc" role="button">
              <span class="visually-hidden">Toggle</span>
              <span class="toggle-icon"></span>
            </a>
          </div>
        </div>
        <div id="toc" data-turbolinks-permanent class="collapse show"></div>
        <div id="toc-data" data-selected="<%= document.id %>"></div>
      </div>

      <div class="col-md-8">
        <div class="tab-content">
          <div class='tab-pane active' id='summary' role='tabpanel'>
            <%= render(partial: 'collection_summary_expanded') %>
          </div>
          <div class='tab-pane' id='description' role='tabpanel'>
            <%= render(partial: 'collection_description') %>
          </div>
          <div class='tab-pane' id='collection-history' role='tabpanel'>
            <%= render(partial: 'collection_history') %>
          </div>
          <div class='tab-pane' id='access' role='tabpanel'>
            <%= render(partial: 'collection_access') %>
          </div>
          <div class='tab-pane' id='find-more' role='tabpanel'>
            <%= render(partial: 'collection_find_more') %>
          </div>
          <nav class="navbar sticky-top">
            <div class="row">
              <div class="col-md-4"></div>
              <div class="col-md-4">
                <a href="#correction" data-bs-toggle="modal" data-bs-target="#correctionModal">
                  <%= image_tag(asset_path('icon-correction.svg'), "aria-label": "suggest correction icon") %>
                  Suggest a correction
                </a>

                <%= render "correction_modal" %>
              </div>
            </div><!-- .row -->
          </nav>
        </div><!-- .tab-content -->
      </div><!-- .col-md-8 -->
    </div><!-- .row.content-container -->
  </div>
</div>

app/views/catalog/_show_collection_header_default.html.erb
<div class='d-md-flex justify-content-between al-show collection header'>
  <nav aria-label="collection header">
    <div class="row">

      <div class="col-md-2">
        <%= link_to(repository_thumbnail, repository_link) %>
      </div>

      <div class="col-md-10">
        <%= render(partial: 'show_collection_title', locals: { document: document.collection_document }) %>
      </div>

    </div>
  </nav>
</div>

app/views/catalog/_table_of_contents_node.html.erb
<li id="<%= parent_node[:id] %>" class="<%= "Selected" if document.id == parent_node[:id] %>">
  <%= link_to "#{solr_document_path(id: parent_node[:id])}" do %>
    <%= parent_node[:title] %>
  <% end %>
  <% if parent_node[:children].present? %>
    <ul>
      <%= render partial: "table_of_contents_node", collection: parent_node[:children], as: :parent_node, locals: { document: document } %>
    </ul>
  <% end %>
</li>